import axios from 'axios';
import config from '../config.js';
import { validatePlugin } from '../middlewares/validator.js';
import { getAutoAiPrompt, cleanAiResponse } from './aiPrompt.js';
import { getVisionModels, getTextModels, compressImageToBase64, postAiWithRetry } from './aiModels.js';

const FORBIDDEN_COMMANDS = ['eval', 'exec', 'delprem', 'addprem', 'backup', 'debug', 'enable', 'disable', 'on', 'off'];

/**
 * Robust parser for [EXEC: .command args] generated by LLMs.
 * Handles Markdown link syntax like [url](url), quotes, nested brackets, and misplaced URL arguments.
 */
export function parseExecCommand(aiText, originalMsgContent = '') {
    if (!aiText || typeof aiText !== 'string') return null;

    const startIdx = aiText.search(/\[EXEC:\s*\./i);
    if (startIdx === -1) return null;

    const afterStart = aiText.slice(startIdx);
    let content = afterStart.replace(/^\[EXEC:\s*/i, '');

    // Strip trailing bracket if closed
    if (content.endsWith(']')) {
        content = content.slice(0, -1);
    } else {
        const lineBreak = content.indexOf('\n');
        if (lineBreak !== -1) {
            content = content.slice(0, lineBreak);
        }
        if (content.endsWith(']')) {
            content = content.slice(0, -1);
        }
    }

    // Clean Markdown link syntax: [title](url) -> url, [url] -> url
    content = content.replace(/\[([^\]]*)\]\((https?:\/\/[^\s\)]+)\)/gi, '$2');
    content = content.replace(/\[(https?:\/\/[^\]]+)\]/gi, '$1');

    // Remove stray quotes, angle brackets, and backticks
    content = content.replace(/[`\"'<>]/g, ' ').trim();

    // Ensure valid command starting with dot
    if (!content.startsWith('.')) {
        const dotIdx = content.indexOf('.');
        if (dotIdx !== -1) content = content.slice(dotIdx);
        else return null;
    }

    const parts = content.slice(1).trim().split(/\s+/).filter(Boolean);
    const targetCmd = parts.shift()?.toLowerCase();
    if (!targetCmd) return null;

    // Clean individual arguments (strip leftover punctuation & brackets)
    let cleanedArgs = parts.map(arg => {
        return arg.replace(/^[\[\(\{\<]+|[\]\)\}\>,\.]+$/g, '').trim();
    }).filter(Boolean);

    // If there is a URL in args, clean it and prioritize it as first argument if needed
    const urlPattern = /(https?:\/\/[^\s]+)/i;
    const urlInArgs = cleanedArgs.find(arg => urlPattern.test(arg));

    if (urlInArgs) {
        const cleanUrl = urlInArgs.match(urlPattern)[0].replace(/[\]\)\>\"'\.,]+$/, '');
        if (!urlPattern.test(cleanedArgs[0])) {
            cleanedArgs = [cleanUrl, ...cleanedArgs.filter(a => a !== urlInArgs)];
        } else {
            cleanedArgs[0] = cleanUrl;
        }
    } else if (originalMsgContent) {
        const urlInMsg = originalMsgContent.match(urlPattern);
        if (urlInMsg) {
            cleanedArgs.unshift(urlInMsg[0].replace(/[\]\)\>\"'\.,]+$/, ''));
        }
    }

    return { targetCmd, args: cleanedArgs };
}

/**
 * Determine quote option based on chat type and media presence.
 * In private chat (PC), do NOT quote unless there is media (image, video, file, document, audio).
 * In group chat, always quote.
 */
export function getQuoteOption(msgData, m) {
    if (!msgData.isGroup) {
        const hasMedia = msgData.isMedia || msgData.isQuotedMedia;
        return hasMedia ? { quoted: m } : {};
    }
    return { quoted: m };
}

/**
 * Handler for Auto AI / AutoGPT (Processes non-command messages when enabled)
 */
export async function handleAutoAi(sock, m, msgData, user, group, setting, plugins) {
    try {
        // Send presence update 'composing' (efek mengetik) for realistic interaction
        if (sock?.sendPresenceUpdate && msgData?.remoteJid) {
            await sock.sendPresenceUpdate('composing', msgData.remoteJid).catch(() => { });
        }

        let session;
        if (msgData.isGroup) {
            const groupNumber = (msgData.remoteJid || '').split('@')[0].replace(/[^0-9]/g, '');
            session = `ryzumi-wabot-${groupNumber}`;
        } else {
            const rawNumber = (msgData.senderJid || m?.sender || '').split('@')[0].replace(/[^0-9]/g, '');
            session = `ryzumi-wabot-${rawNumber || 'user'}`;
        }

        // Media inspection (Direct message or Quoted message)
        let imageUrl = null;
        const isMediaImage = msgData.isMedia && /image/i.test(msgData.mime);
        const isQuotedImage = msgData.isQuotedMedia && /image/i.test(msgData.quotedMime);

        const hasAnyMedia = msgData.isMedia || msgData.isQuotedMedia;
        let mediaDescription = '';
        if (isMediaImage || isQuotedImage) {
            mediaDescription = 'gambar/foto';
        } else if ((msgData.isMedia && /video/i.test(msgData.mime)) || (msgData.isQuotedMedia && /video/i.test(msgData.quotedMime))) {
            mediaDescription = 'video/gif';
        } else if ((msgData.isMedia && /sticker|webp/i.test(msgData.mime)) || (msgData.isQuotedMedia && /sticker|webp/i.test(msgData.quotedMime))) {
            mediaDescription = 'stiker';
        } else if ((msgData.isMedia && /audio/i.test(msgData.mime)) || (msgData.isQuotedMedia && /audio/i.test(msgData.quotedMime))) {
            mediaDescription = 'audio/musik';
        } else if (hasAnyMedia) {
            mediaDescription = 'dokumen/file';
        }

        // Try processing and compressing image to base64 if present
        if (isMediaImage || isQuotedImage) {
            try {
                const buffer = await msgData.downloadMedia();
                if (buffer) {
                    imageUrl = await compressImageToBase64(buffer);
                }
            } catch (err) {
                console.warn('Auto AI image processing failed:', err.message);
            }
        }

        // Dynamically build list of available commands and descriptions for the AI model
        const cmdList = plugins
            .filter(p => p.command && !p.isOwner && p.category !== 'owner')
            .map(p => `.${p.command[0]}: ${p.description || p.category}`)
            .join('\n');

        const prompt = getAutoAiPrompt(cmdList);

        // Fetch dynamic active models from API (strictly excluding Claude)
        const visionModels = await getVisionModels({ allowClaude: false });
        const textModels = await getTextModels({ allowClaude: false });

        let baseContent = msgData.messageContent || '';
        if (msgData.isQuoted && msgData.quotedContent && !baseContent.includes(msgData.quotedContent)) {
            baseContent = baseContent
                ? `[Pesan yang di-reply]: "${msgData.quotedContent}"\n\n[Pertanyaan/Pesan]: ${baseContent}`
                : msgData.quotedContent;
        }

        let inputContent = baseContent;

        let data = null;

        // 1. Attempt Vision Model if Image is available
        if (imageUrl) {
            const visionInput = inputContent || 'Jelaskan gambar ini';
            for (const modelName of visionModels) {
                try {
                    const payload = {
                        text: visionInput,
                        model: modelName,
                        prompt: prompt,
                        session: session,
                        image: imageUrl
                    };
                    data = await postAiWithRetry(`${config.API_RYZUMI}/api/ai/post/vision-model`, payload, {
                        retries: 3,
                        timeout: 20000,
                        delayMs: 1000
                    });
                    if (data?.result) break;
                } catch (err) {
                    console.warn(`Auto AI vision model '${modelName}' failed after retries: ${err.message}`);
                }
            }
        }

        // 2. Fallback to Text Model (or primary handler if no image / vision failed)
        if (!data || !data.result) {
            // Annotate media context if media is attached so text-model understands user intent (e.g. "Buatin jadi sticker")
            let textModelInput = baseContent;
            if (mediaDescription) {
                textModelInput = `[Lampiran Media: User melampirkan media ${mediaDescription}]\n\n[Pesan/Caption User]: ${baseContent || '(tidak ada caption)'}`;
            }

            if (!textModelInput) {
                textModelInput = 'Halo Ryzumi!';
            }

            for (const modelName of textModels) {
                try {
                    const payload = {
                        text: textModelInput,
                        model: modelName,
                        prompt: prompt,
                        session: session
                    };
                    data = await postAiWithRetry(`${config.API_RYZUMI}/api/ai/post/text-model`, payload, {
                        retries: 2,
                        timeout: 15000,
                        delayMs: 1000
                    });
                    if (data?.result) break;
                } catch (err) {
                    console.warn(`Auto AI text model '${modelName}' failed after retries: ${err.message}`);
                }
            }
        }

        if (!data || !data.result) {
            return;
        }

        const fullResult = data.result;

        // Parse tool/function execution from AI response
        const parsed = parseExecCommand(fullResult, msgData.messageContent);

        // Strip EXEC tags from conversational response
        const rawTextOnly = fullResult.replace(/`?\[EXEC:\s*[^\]]+\]`?/gi, '').trim();
        const textOnly = cleanAiResponse(rawTextOnly);

        const quoteOptions = getQuoteOption(msgData, m);

        if (parsed && parsed.targetCmd) {
            const { targetCmd, args } = parsed;

            if (FORBIDDEN_COMMANDS.includes(targetCmd)) {
                if (textOnly) {
                    await sock.sendMessage(msgData.remoteJid, { text: textOnly }, quoteOptions);
                } else {
                    await sock.sendMessage(msgData.remoteJid, {
                        text: `Uwaaa! Perintah itu tidak diizinkan demi keamanan bot kak~ (｡T ω T｡)`
                    }, quoteOptions);
                }
                return;
            }

            const targetPlugin = plugins.find(p => p.command && p.command.includes(targetCmd));

            if (!targetPlugin) {
                if (textOnly) {
                    await sock.sendMessage(msgData.remoteJid, { text: textOnly }, quoteOptions);
                }
                return;
            }

            if (targetPlugin.isOwner && !user.isOwner) {
                await sock.sendMessage(msgData.remoteJid, {
                    text: `Aduuh! Perintah ini khusus untuk Owner Ryzumi kak~ (｡T ω T｡)`
                }, quoteOptions);
                return;
            }

            // Create simulated msgData for target plugin execution with sanitized arguments
            const simMsgData = {
                ...msgData,
                commandName: targetCmd,
                args: args,
                messageContent: `.${targetCmd} ${args.join(' ')}`.trim()
            };

            const isValid = await validatePlugin(sock, m, simMsgData, user, group, targetPlugin, setting);
            if (isValid) {
                await targetPlugin.execute(sock, m, simMsgData, user, group, plugins);
            }
        } else if (textOnly) {
            await sock.sendMessage(msgData.remoteJid, { text: textOnly }, quoteOptions);
        }

    } catch (error) {
        console.error('Auto AI Handler Error:', error);
    }
}
